apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-on-k8s
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "khanhdang/spark-k8s-app:1.0"
  imagePullPolicy: Always
  mainClass: ghn.vn.spark.Test
  mainApplicationFile: local:///app/spark-jobs.jar
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    envSecretKeyRefs:
      GCP_KEY:
        name: gcp-credentials
        key: GCP_KEY
  executor:
    cores: 1
    instances: 2
    memory: "1000m"
    labels:
      version: 3.1.1