apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
 name: pyspark-on-k8s
 namespace: spark-everywhere
spec:
 type: Python
 pythonVersion: "3"
 mode: cluster
 image: "khanhdang/spark-k8s:latest"
 imagePullPolicy: Always
 mainApplicationFile: "local:///app/spark_on_k8s_app.py"
 sparkVersion: "3.1.1"
 restartPolicy:
   type: Never
 volumes:
   - name: "test-volume"
     hostPath:
       path: "/tmp"
       type: Directory
 driver:
   cores: 1
   coreLimit: "1200m"
   memory: "512m"
   labels:
     version: 3.1.1
   serviceAccount: spark-account
   volumeMounts:
     - name: "test-volume"
       mountPath: "/tmp"
 executor:
   cores: 1
   instances: 1
   memory: "1g"
   labels:
     version: 3.1.1
   volumeMounts:
     - name: "test-volume"
       mountPath: "/tmp"
